python RunAnalysis.py --board P_4 --PA TTV2_02 --mode batch
python RunAnalysis.py --board P_1_mini1 --PA TTV2_08 --mode batch
python RunAnalysis.py --board P_1_mini2 --PA TTV1_02 --mode batch
python RunAnalysis.py --board P_1_mini6 --PA TTV1_01 --mode batch
python RunAnalysis.py --board P_1_mini7 --PA TTV2_03 --mode batch
python RunAnalysis.py --board P_3_mini1 --PA TTV2_08 --mode batch
python RunAnalysis.py --board P_3_mini6 --PA TTV2_06 --mode batch
python RunAnalysis.py --board P_3_mini7 --PA TTV2_06 --mode batch
python RunAnalysis.py --board P_4_mini1 --PA TTV1_02 --mode batch
python RunAnalysis.py --board P_4_mini2 --PA TTV2_07 --mode batch
python RunAnalysis.py --board P_4_mini6 --PA TTV2_07 --mode batch
python RunAnalysis.py --board P_4_mini7 --PA TTV1_01 --mode batch
